// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKbtcTv89INoyC-LMeer0o5tdBGMGiKtc',
    appId: '1:532736115387:web:5c217790572c9206e39f9e',
    messagingSenderId: '532736115387',
    projectId: 'nexoeshop',
    authDomain: 'nexoeshop.firebaseapp.com',
    storageBucket: 'nexoeshop.firebasestorage.app',
    measurementId: 'G-FHWRWC4Z2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP0AnxRO343ZeDEuvIzUlb3KwG3MzNOJM',
    appId: '1:532736115387:android:fae1217010351229e39f9e',
    messagingSenderId: '532736115387',
    projectId: 'nexoeshop',
    storageBucket: 'nexoeshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWv6AETHCD_07PALJfESq2ocU4ngzn3pw',
    appId: '1:532736115387:ios:4d4deb97046167b3e39f9e',
    messagingSenderId: '532736115387',
    projectId: 'nexoeshop',
    storageBucket: 'nexoeshop.firebasestorage.app',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWv6AETHCD_07PALJfESq2ocU4ngzn3pw',
    appId: '1:532736115387:ios:4d4deb97046167b3e39f9e',
    messagingSenderId: '532736115387',
    projectId: 'nexoeshop',
    storageBucket: 'nexoeshop.firebasestorage.app',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKbtcTv89INoyC-LMeer0o5tdBGMGiKtc',
    appId: '1:532736115387:web:279f6b2a5c7011e8e39f9e',
    messagingSenderId: '532736115387',
    projectId: 'nexoeshop',
    authDomain: 'nexoeshop.firebaseapp.com',
    storageBucket: 'nexoeshop.firebasestorage.app',
    measurementId: 'G-VV80XWHFS3',
  );
}
